// Generated by https://quicktype.io

export interface SignupModel {
  id: number;
  name: string;
  surname: string;
  email: string;
  auth: Auth;
}

export interface Auth {
  login: string;
  password: string;
  roles: number;
}
