// Generated by https://quicktype.io

import { UserDetailsResponse } from './user.model';

export interface ProfileResponse {
  id: number;
  age: number;
  gender: number;
  weight: number;
  target: number;
  height: number;
  isVeg: boolean;
  userId: number;
  activityLevel: number;
  goal: number;
  pace: number;
  user: UserModel;
}
// Generated by https://quicktype.io

export interface UserModel {
  id: number;
  name: string;
  surname: string;
  email: string;
}
