// Generated by https://quicktype.io

export interface ProgressList {
  count: number;
  list: Progress[];
}

export interface Progress {
  id: number;
  userId: number;
  date: string;
  weight: number;
}
