// Generated by https://quicktype.io

export interface Rating {
  id: number;
  userId: number;
  foodId: number;
  rating: number;
  date: string;
}

export interface RatingWithName extends Rating {
  name?: string;
}
