// Generated by https://quicktype.io

export interface BMIDetail {
  weight: number;
  height: number;
  bmiValue: number;
  userId: number;
}

// Generated by https://quicktype.io

export interface HealthDetail {
  underWeightCount: number;
  overWeightCount: number;
  healthyCount: number;
  date: string;
}
