// Generated by https://quicktype.io

export interface BMIDetail {
  weight: number;
  height: number;
  bmiValue: number;
  userId: number;
}

// Generated by https://quicktype.io

export interface HealthDetail {
  underWeightCount: number;
  overWeightCount: number;
  healthyCount: number;
  date: string;
}

// Generated by https://quicktype.io

export interface TopUser {
  userId: number;
  fullName: string;
  weight: number;
  change: number;
  percentage: number;
}
